<?php

namespace AppBundle\Repository;

/**
 * GuestbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestbookRepository extends \Doctrine\ORM\EntityRepository
{
  public function getListBy($criteria = null)
  {
    $qb = $this->createQueryBuilder('gb');

    if (!empty($criteria['query'])) {
      $qb->where('gb.name LIKE :q');
      $qb->orWhere('gb.comment LIKE :q');
      $qb->setParameter(':q', '%'.$criteria['query'].'%');
    }

    $qb->orderBy('gb.created_at', 'DESC');

    return $qb->getQuery();
  }

  public function getLatestPosts($limit = null)
  {
    $qb = $this->createQueryBuilder('gb')
      ->addOrderBy('gb.created_at', 'DESC');

    if (false === is_null($limit))
      $qb->setMaxResults($limit);

    return $qb->getQuery()->getResult();
  }
}
